- name: Docker, Node, Npm installation 
  hosts: vps
  become: yes
 
  tasks:
    - name: Update dnf
      ansible.builtin.dnf:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.dnf:
        name:
           - docker-ce
           - docker-ce-cli
           - containerd.io
           - docker-compose-plugin
           - nodejs
           - npm
        state: present
