---
- name: Install packages
  hosts: all
  become: true

  vars:
    packages:
      - podman
      - nodejs
      - npm

  tasks:
    - name: Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: present
